require("dotenv").config();

module.exports = {
  port: 3002,
  mongoURI: process.env.BOT_TOKEN,
  ownerids: ["01GPZ5PTPQ2RNMZEF02NKD7TQE"],
  modids: ["01GPZ5PTPQ2RNMZEF02NKD7TQE", "01GQ3NS0EB3FF8V2Q6KHX887DS", "01FHZCM5J1T2DP08N9MCTYP4DT"],
  bot: {
      prefix: "gc!",
      rblApiKey: process.env.RBL_APIKEY,
      token: process.env.BOT_TOKEN
  },
  channels: {
      globalLogs: "01H2BSM2RDAYTQJWK22HZWEZBV"
  },
  bannedWords: [
      "nigga",
      "nigger",
      "https://rvlt.gg/",
      "rvlt.gg/",
      "https://app.revolt.chat/invite",
      "cunt",
      "fuck you",
      "fuckyou",
      "fuck-you",
      "faggot",
      "fag",
      "fagot",
      "fuckface",
      "cracker",
      "cuntface",
      "jerkoff",
      "fuckme",
      "anal",
      "anus",
      "arse",
      "ass",
      "ballsack",
      "balls",
      "bastard",
      "bitch",
      "biatch",
      "bloody",
      "blowjob",
      "blow job",
      "bollock",
      "bollok",
      "boner",
      "boob",
      "bugger",
      "bum",
      "butt",
      "buttplug",
      "clitoris",
      "cock",
      "coon",
      "crap",
      "cunt",
      "damn",
      "dick",
      "dildo",
      "dyke",
      "fag",
      "feck",
      "fellate",
      "fellatio",
      "felching",
      "fuck",
      "f u c k",
      "fudgepacker",
      "fudge packer",
      "flange",
      "homo",
      "jerk",
      "jizz",
      "knobend",
      "knob end",
      "labia",
      "muff",
      "nigger",
      "nigga",
      "omg",
      "penis",
      "piss",
      "poop",
      "prick",
      "pube",
      "pussy",
      "queer",
      "scrotum",
      "sex",
      "shit",
      "s hit",
      "sh1t",
      "slut",
      "smegma",
      "spunk",
      "tit",
      "tosser",
      "turd",
      "twat",
      "vagina",
      "wank",
      "whore",
  ]
}